add_subdirectory(test.unit.stlsoft.error.active_end_iterator_exhaustion)
add_subdirectory(test.unit.stlsoft.error.contract_violation)
add_subdirectory(test.unit.stlsoft.error.conversion_error)
add_subdirectory(test.unit.stlsoft.error.errno_scope)
add_subdirectory(test.unit.stlsoft.error.error_desc)
add_subdirectory(test.unit.stlsoft.error.external_iterator_invalidation)
add_subdirectory(test.unit.stlsoft.error.iteration_interruption)
add_subdirectory(test.unit.stlsoft.error.unrecoverable)

# ############################## end of file ############################# #
