# SIS:AUTO_GENERATED: Remove this line if you edit the file, otherwise it will be overwritten
add_subdirectory(handles)
add_subdirectory(test.component.stlsoft.filesystem.io_functions)
add_subdirectory(test.component.stlsoft.filesystem.path_buffer)
add_subdirectory(test.component.stlsoft.filesystem.searchspec_sequence)
