add_subdirectory(test.unit.atlstl.automation.automation_collections)
add_subdirectory(test.unit.atlstl.automation.enumerators)
add_subdirectory(test.unit.atlstl.automation.multiple_dispatch)
add_subdirectory(test.unit.atlstl.automation.property_method_helpers)


# ############################## end of file ############################# #
