# SIS:AUTO_GENERATED: Remove this line if you edit the file, otherwise it will be overwritten
add_subdirectory(test.unit.atlstl.automation.automation_collections)
add_subdirectory(test.unit.atlstl.automation.enumerators)
add_subdirectory(test.unit.atlstl.automation.multiple_dispatch)
add_subdirectory(test.unit.atlstl.automation.property_method_helpers)
