# SIS:AUTO_GENERATED: Remove this line if you edit the file, otherwise it will be overwritten
add_subdirectory(test.unit.comstl.util.C.CY_functions)
add_subdirectory(test.unit.comstl.util.C.DECIMAL_functions)
add_subdirectory(test.unit.comstl.util.C.GUID_functions)
add_subdirectory(test.unit.comstl.util.C.VARIANT_functions)
add_subdirectory(test.unit.comstl.util.C.object_functions)
add_subdirectory(test.unit.comstl.util.C.refcount_functions)
add_subdirectory(test.unit.comstl.util.C.stream_functions)
add_subdirectory(test.unit.comstl.util.acyclic_connector)
add_subdirectory(test.unit.comstl.util.creation_functions)
add_subdirectory(test.unit.comstl.util.guid)
add_subdirectory(test.unit.comstl.util.initialisers)
add_subdirectory(test.unit.comstl.util.interface_traits)
add_subdirectory(test.unit.comstl.util.object_functions)
add_subdirectory(test.unit.comstl.util.refcount_functions)
add_subdirectory(test.unit.comstl.util.stream_functions)
add_subdirectory(test.unit.comstl.util.value_policies)
add_subdirectory(test.unit.comstl.util.variant)
