add_subdirectory(test.unit.stlsoft.iterator.FILE_iterator)
add_subdirectory(test.unit.stlsoft.iterator.associative_eraser_iterator)
add_subdirectory(test.unit.stlsoft.iterator.associative_select_iterator)
add_subdirectory(test.unit.stlsoft.iterator.eraser_iterator)
add_subdirectory(test.unit.stlsoft.iterator.member_selector)
add_subdirectory(test.unit.stlsoft.iterator.push_insert_iterator)
add_subdirectory(test.unit.stlsoft.iterator.push_inserter)
add_subdirectory(test.unit.stlsoft.iterator.string_concatenator)
add_subdirectory(test.unit.stlsoft.iterator.string_concatenator_iterator)
add_subdirectory(test.unit.stlsoft.iterator.string_insert_iterator)
add_subdirectory(test.unit.stlsoft.iterator.transformer)

# ############################## end of file ############################# #
