# SIS:AUTO_GENERATED: Remove this line if you edit the file, otherwise it will be overwritten
add_subdirectory(handles)
add_subdirectory(test.component.winstl.filesystem.C.memory_map_functions)
add_subdirectory(test.component.winstl.filesystem.absolute_path)
add_subdirectory(test.component.winstl.filesystem.current_directory)
add_subdirectory(test.component.winstl.filesystem.current_directory_scope)
add_subdirectory(test.component.winstl.filesystem.directory_functions)
add_subdirectory(test.component.winstl.filesystem.file_creation_functions)
add_subdirectory(test.component.winstl.filesystem.file_functions)
add_subdirectory(test.component.winstl.filesystem.file_information_functions)
add_subdirectory(test.component.winstl.filesystem.file_path_buffer)
add_subdirectory(test.component.winstl.filesystem.filesystem_traits)
add_subdirectory(test.component.winstl.filesystem.findfile_sequence)
add_subdirectory(test.component.winstl.filesystem.findvolume_sequence)
add_subdirectory(test.component.winstl.filesystem.functionals)
add_subdirectory(test.component.winstl.filesystem.link_functions)
add_subdirectory(test.component.winstl.filesystem.memory_map_functions)
add_subdirectory(test.component.winstl.filesystem.memory_map_sparse_region_functions)
add_subdirectory(test.component.winstl.filesystem.memory_mapped_file)
add_subdirectory(test.component.winstl.filesystem.path)
add_subdirectory(test.component.winstl.filesystem.path_buffer)
add_subdirectory(test.component.winstl.filesystem.path_classify_functions)
add_subdirectory(test.component.winstl.filesystem.path_functions)
add_subdirectory(test.component.winstl.filesystem.path_parse_functions)
add_subdirectory(test.component.winstl.filesystem.pipe)
add_subdirectory(test.component.winstl.filesystem.readdir_sequence)
add_subdirectory(test.component.winstl.filesystem.readonly_memory_mapped_file)
