add_subdirectory(refcount_policies)
add_subdirectory(test.unit.stlsoft.synch.checkout_token)
add_subdirectory(test.unit.stlsoft.synch.concepts)
add_subdirectory(test.unit.stlsoft.synch.lock_scope)
add_subdirectory(test.unit.stlsoft.synch.null_mutex)
add_subdirectory(test.unit.stlsoft.synch.singlethreaded_tss_index)
add_subdirectory(test.unit.stlsoft.synch.spin_mutex_base)

# ############################## end of file ############################# #
