# SIS:AUTO_GENERATED: Remove this line if you edit the file, otherwise it will be overwritten
add_subdirectory(refcount_policies)
add_subdirectory(test.unit.stlsoft.synch.checkout_token)
add_subdirectory(test.unit.stlsoft.synch.concepts)
add_subdirectory(test.unit.stlsoft.synch.lock_scope)
add_subdirectory(test.unit.stlsoft.synch.null_mutex)
add_subdirectory(test.unit.stlsoft.synch.singlethreaded_tss_index)
add_subdirectory(test.unit.stlsoft.synch.spin_mutex_base)
