# SIS:AUTO_GENERATED: Remove this line if you edit the file, otherwise it will be overwritten
add_subdirectory(test.component.stlsoft.diagnostics.std_chrono_hrc_stopwatch)
add_subdirectory(test.component.stlsoft.diagnostics.stopwatch_initialiser)
add_subdirectory(test.component.stlsoft.diagnostics.stopwatch_scope)
