# SIS:AUTO_GENERATED: Remove this line if you edit the file, otherwise it will be overwritten
add_subdirectory(test.unit.winstl.shims.conversion.to_DATE)
add_subdirectory(test.unit.winstl.shims.conversion.to_FILETIME)
add_subdirectory(test.unit.winstl.shims.conversion.to_SYSTEMTIME)
add_subdirectory(test.unit.winstl.shims.conversion.to_uint64)
add_subdirectory(to_DATE)
add_subdirectory(to_FILETIME)
add_subdirectory(to_SYSTEMTIME)
add_subdirectory(to_uint64)
