add_subdirectory(algorithms)
add_subdirectory(collections)
add_subdirectory(containers)
add_subdirectory(conversion)
add_subdirectory(diagnostics)
add_subdirectory(error)
add_subdirectory(exception)
add_subdirectory(exceptions)
add_subdirectory(filesystem)
add_subdirectory(function_adaptors)
add_subdirectory(functional)
add_subdirectory(iterator)
add_subdirectory(iterators)
add_subdirectory(limits)
add_subdirectory(locale)
add_subdirectory(memory)
add_subdirectory(performance)
add_subdirectory(properties)
add_subdirectory(shims)
add_subdirectory(smartptr)
add_subdirectory(std)
add_subdirectory(string)
add_subdirectory(synch)
add_subdirectory(system)
add_subdirectory(time)
add_subdirectory(traits)
add_subdirectory(util)

# ############################## end of file ############################# #
