# SIS:AUTO_GENERATED: Remove this line if you edit the file, otherwise it will be overwritten
add_subdirectory(test.unit.platformstl.exception.access_exception)
add_subdirectory(test.unit.platformstl.exception.entry_not_found_exception)
add_subdirectory(test.unit.platformstl.exception.file_not_found_exception)
add_subdirectory(test.unit.platformstl.exception.invalid_entry_type_exception)
add_subdirectory(test.unit.platformstl.exception.invalid_file_type_exception)
add_subdirectory(test.unit.platformstl.exception.platformstl_exception)
add_subdirectory(test.unit.platformstl.exception.security_exception)
add_subdirectory(test.unit.platformstl.exception.throw_policies)
