# SIS:AUTO_GENERATED: Remove this line if you edit the file, otherwise it will be overwritten
add_subdirectory(test.unit.stlsoft.shims.attribute.get_top.std.deque)
add_subdirectory(test.unit.stlsoft.shims.attribute.get_top.std.list)
add_subdirectory(test.unit.stlsoft.shims.attribute.get_top.std.priority_queue)
add_subdirectory(test.unit.stlsoft.shims.attribute.get_top.std.queue)
add_subdirectory(test.unit.stlsoft.shims.attribute.get_top.std.stack)
add_subdirectory(test.unit.stlsoft.shims.attribute.get_top.std.vector)
