add_subdirectory(test.unit.stlsoft.shims.attribute.get_ptr.std.fundamental)
add_subdirectory(test.unit.stlsoft.shims.attribute.get_ptr.std.shared_ptr)
add_subdirectory(test.unit.stlsoft.shims.attribute.get_ptr.std.unique_ptr)

# ############################## end of file ############################# #
