add_subdirectory(std)
add_subdirectory(test.unit.stlsoft.algorithms.bounded)
add_subdirectory(test.unit.stlsoft.algorithms.collection)
add_subdirectory(test.unit.stlsoft.algorithms.debug)
add_subdirectory(test.unit.stlsoft.algorithms.deprecated)
add_subdirectory(test.unit.stlsoft.algorithms.pod)
add_subdirectory(test.unit.stlsoft.algorithms.unordered)

# ############################## end of file ############################# #
