# SIS:AUTO_GENERATED: Remove this line if you edit the file, otherwise it will be overwritten
add_subdirectory(test.component.winstl.system.directory_functions.C)
add_subdirectory(test.component.winstl.system.directory_functions)
add_subdirectory(test.component.winstl.system.environment_block)
add_subdirectory(test.component.winstl.system.environment_sequence)
add_subdirectory(test.component.winstl.system.environment_variable)
add_subdirectory(test.component.winstl.system.home_directory)
add_subdirectory(test.component.winstl.system.module_directory)
add_subdirectory(test.component.winstl.system.module_filename)
add_subdirectory(test.component.winstl.system.pid_sequence)
add_subdirectory(test.component.winstl.system.process_module_sequence)
add_subdirectory(test.component.winstl.system.searchpath_sequence)
add_subdirectory(test.component.winstl.system.system_directory)
add_subdirectory(test.component.winstl.system.temporary_directory)
add_subdirectory(test.component.winstl.system.windows_directory)
