# SIS:AUTO_GENERATED: Remove this line if you edit the file, otherwise it will be overwritten
add_subdirectory(test.unit.stlsoft.util.std.dinkumware_iterator_traits)
add_subdirectory(test.unit.stlsoft.util.std.iterator_category_limiters)
add_subdirectory(test.unit.stlsoft.util.std.iterator_generators)
add_subdirectory(test.unit.stlsoft.util.std.iterator_helper)
add_subdirectory(test.unit.stlsoft.util.std.library_discriminator)
add_subdirectory(test.unit.stlsoft.util.std.stdio_overload_detectors)
add_subdirectory(test.unit.stlsoft.util.std.utility)
