# SIS:AUTO_GENERATED: Remove this line if you edit the file, otherwise it will be overwritten
add_subdirectory(common)
add_subdirectory(test.unit.stlsoft.iterators.adapted_iterator_traits)
add_subdirectory(test.unit.stlsoft.iterators.associative_select_iterator)
add_subdirectory(test.unit.stlsoft.iterators.c_str_inserter)
add_subdirectory(test.unit.stlsoft.iterators.contiguous_diluter_iterator)
add_subdirectory(test.unit.stlsoft.iterators.cstring_concatenator_iterator)
add_subdirectory(test.unit.stlsoft.iterators.filter_iterator)
add_subdirectory(test.unit.stlsoft.iterators.filter_transform_iterator)
add_subdirectory(test.unit.stlsoft.iterators.index_iterator)
add_subdirectory(test.unit.stlsoft.iterators.indirect_reverse_iterator)
add_subdirectory(test.unit.stlsoft.iterators.member_selector_iterator)
add_subdirectory(test.unit.stlsoft.iterators.null_output_iterator)
add_subdirectory(test.unit.stlsoft.iterators.ostream_iterator)
add_subdirectory(test.unit.stlsoft.iterators.string_concatenator_iterator)
add_subdirectory(test.unit.stlsoft.iterators.transform_filter_iterator)
add_subdirectory(test.unit.stlsoft.iterators.transform_iterator)
add_subdirectory(test.unit.stlsoft.iterators.unary_function_output_iterator_adaptor)
