# SIS:AUTO_GENERATED: Remove this line if you edit the file, otherwise it will be overwritten
add_subdirectory(test.unit.winstl.shims.attribute.get_HKEY)
add_subdirectory(test.unit.winstl.shims.attribute.get_HWND)
add_subdirectory(test.unit.winstl.shims.attribute.get_kernel_handle)
add_subdirectory(test.unit.winstl.shims.attribute.get_os_file_handle)
add_subdirectory(test.unit.winstl.shims.attribute.get_synch_handle)
