# SIS:AUTO_GENERATED: Remove this line if you edit the file, otherwise it will be overwritten
add_subdirectory(test.unit.winstl.performance.highperformance_counter)
add_subdirectory(test.unit.winstl.performance.multimedia_counter)
add_subdirectory(test.unit.winstl.performance.performance_counter)
add_subdirectory(test.unit.winstl.performance.systemtime_counter)
add_subdirectory(test.unit.winstl.performance.threadtimes_counter)
add_subdirectory(test.unit.winstl.performance.tick_counter)
