# SIS:AUTO_GENERATED: Remove this line if you edit the file, otherwise it will be overwritten
add_subdirectory(c_string.strnicmp)
add_subdirectory(c_string.strnicmp.C)
add_subdirectory(c_string_traits)
add_subdirectory(char_traits)
add_subdirectory(copy_functions)
add_subdirectory(exception_string)
add_subdirectory(functionals.string_begins_with)
add_subdirectory(shim_string)
add_subdirectory(simple_string)
add_subdirectory(static_string)
add_subdirectory(string_slice)
add_subdirectory(string_view)
