# SIS:AUTO_GENERATED: Remove this line if you edit the file, otherwise it will be overwritten
add_subdirectory(c_string)
add_subdirectory(test.unit.stlsoft.string.C.copy_functions)
add_subdirectory(test.unit.stlsoft.string.c_string_traits)
add_subdirectory(test.unit.stlsoft.string.case_functions)
add_subdirectory(test.unit.stlsoft.string.char_alt_traits)
add_subdirectory(test.unit.stlsoft.string.char_traits)
add_subdirectory(test.unit.stlsoft.string.charset_tokeniser)
add_subdirectory(test.unit.stlsoft.string.container_slice_functions)
add_subdirectory(test.unit.stlsoft.string.copy_functions)
add_subdirectory(test.unit.stlsoft.string.cstring_functions)
add_subdirectory(test.unit.stlsoft.string.cstring_maker)
add_subdirectory(test.unit.stlsoft.string.ctype_traits)
add_subdirectory(test.unit.stlsoft.string.exception_string)
add_subdirectory(test.unit.stlsoft.string.fast_string_concatenator)
add_subdirectory(test.unit.stlsoft.string.functionals)
add_subdirectory(test.unit.stlsoft.string.replace_functions)
add_subdirectory(test.unit.stlsoft.string.shim_string)
if(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC" AND MSVC_VERSION LESS 1200)
	add_subdirectory(test.unit.stlsoft.string.shim_string_vc5_)
endif()
add_subdirectory(test.unit.stlsoft.string.simple_string)
add_subdirectory(test.unit.stlsoft.string.slice_functions)
add_subdirectory(test.unit.stlsoft.string.special_string_instance)
add_subdirectory(test.unit.stlsoft.string.split_functions)
add_subdirectory(test.unit.stlsoft.string.static_string)
add_subdirectory(test.unit.stlsoft.string.string_slice)
add_subdirectory(test.unit.stlsoft.string.string_tokeniser)
add_subdirectory(test.unit.stlsoft.string.string_traits)
add_subdirectory(test.unit.stlsoft.string.string_traits_fwd)
add_subdirectory(test.unit.stlsoft.string.string_view)
add_subdirectory(test.unit.stlsoft.string.tokeniser_functions)
add_subdirectory(test.unit.stlsoft.string.trim_functions)
add_subdirectory(test.unit.stlsoft.string.view_slice_functions)
