# SIS:AUTO_GENERATED: Remove this line if you edit the file, otherwise it will be overwritten
add_subdirectory(get_FILE_ptr)
add_subdirectory(get_ptr)
add_subdirectory(get_top)
add_subdirectory(test.unit.stlsoft.shims.attribute.get_FILE_ptr)
add_subdirectory(test.unit.stlsoft.shims.attribute.get_ptr)
add_subdirectory(test.unit.stlsoft.shims.attribute.get_top)
