# SIS:AUTO_GENERATED: Remove this line if you edit the file, otherwise it will be overwritten
add_subdirectory(scoped_handle)
add_subdirectory(test.unit.stlsoft.smartptr.proxy_ptr)
add_subdirectory(test.unit.stlsoft.smartptr.ref_ptr)
add_subdirectory(test.unit.stlsoft.smartptr.scoped_handle)
add_subdirectory(test.unit.stlsoft.smartptr.scoped_lambda)
add_subdirectory(test.unit.stlsoft.smartptr.scoped_method)
add_subdirectory(test.unit.stlsoft.smartptr.shared_ptr)
