# SIS:AUTO_GENERATED: Remove this line if you edit the file, otherwise it will be overwritten
add_subdirectory(test.unit.stlsoft.util.bits.count_functions)
add_subdirectory(test.unit.stlsoft.util.bits.count_functions.C)
add_subdirectory(test.unit.stlsoft.util.bits.test_functions)
add_subdirectory(test.unit.stlsoft.util.bits.test_functions.C)
add_subdirectory(test.unit.stlsoft.util.bits.xor_functions)
add_subdirectory(test.unit.stlsoft.util.bits.xor_functions.C)
