# SIS:AUTO_GENERATED: Remove this line if you edit the file, otherwise it will be overwritten
add_subdirectory(test.unit.stlsoft.shims.access.string.std.basic_string)
add_subdirectory(test.unit.stlsoft.shims.access.string.std.basic_string_view)
add_subdirectory(test.unit.stlsoft.shims.access.string.std.c_string)
add_subdirectory(test.unit.stlsoft.shims.access.string.std.chrono)
add_subdirectory(test.unit.stlsoft.shims.access.string.std.exception)
add_subdirectory(test.unit.stlsoft.shims.access.string.std.nullptr)
add_subdirectory(test.unit.stlsoft.shims.access.string.std.time)
add_subdirectory(test.unit.stlsoft.shims.access.string.std.type_info)
