# SIS:AUTO_GENERATED: Remove this line if you edit the file, otherwise it will be overwritten
add_subdirectory(test.component.winstl.diagnostics.highperformance_stopwatch)
add_subdirectory(test.component.winstl.diagnostics.multimedia_stopwatch)
add_subdirectory(test.component.winstl.diagnostics.processtimes_stopwatch)
add_subdirectory(test.component.winstl.diagnostics.stopwatch)
add_subdirectory(test.component.winstl.diagnostics.systemtime_stopwatch)
add_subdirectory(test.component.winstl.diagnostics.threadtimes_stopwatch)
add_subdirectory(test.component.winstl.diagnostics.tick_stopwatch)
