# SIS:AUTO_GENERATED: Remove this line if you edit the file, otherwise it will be overwritten
add_subdirectory(test.unit.unixstl.synch.atomic_types)
add_subdirectory(test.unit.unixstl.synch.common)
add_subdirectory(test.unit.unixstl.synch.exceptions)
add_subdirectory(test.unit.unixstl.synch.spin_mutex_policies)
