# SIS:AUTO_GENERATED: Remove this line if you edit the file, otherwise it will be overwritten
add_subdirectory(test.unit.mfcstl.collections.CArray_adaptors)
add_subdirectory(test.unit.mfcstl.collections.CArray_swap)
add_subdirectory(test.unit.mfcstl.collections.CArray_traits)
add_subdirectory(test.unit.mfcstl.collections.CList_adaptors)
add_subdirectory(test.unit.mfcstl.collections.CList_swap)
add_subdirectory(test.unit.mfcstl.collections.CList_traits)
add_subdirectory(test.unit.mfcstl.collections.CString_adaptors)
