# SIS:AUTO_GENERATED: Remove this line if you edit the file, otherwise it will be overwritten
add_subdirectory(test.component.unixstl.synch.atomic_functions)
add_subdirectory(test.component.unixstl.synch.atomic_functions.C)
add_subdirectory(test.component.unixstl.synch.process_mutex)
add_subdirectory(test.component.unixstl.synch.semaphore)
add_subdirectory(test.component.unixstl.synch.sleep_functions)
add_subdirectory(test.component.unixstl.synch.sleep_functions.C)
add_subdirectory(test.component.unixstl.synch.spin_mutex)
add_subdirectory(test.component.unixstl.synch.thread_mutex)
add_subdirectory(test.component.unixstl.synch.tss_index)
