add_subdirectory(bits)
add_subdirectory(count_digits)
add_subdirectory(std)
add_subdirectory(streams)
add_subdirectory(string)
add_subdirectory(test.unit.stlsoft.util.argument_proxies)
add_subdirectory(test.unit.stlsoft.util.bit_functions)
add_subdirectory(test.unit.stlsoft.util.compiler_optimisation_traits)
add_subdirectory(test.unit.stlsoft.util.constraints)
add_subdirectory(test.unit.stlsoft.util.count_decimal_digits)
add_subdirectory(test.unit.stlsoft.util.count_digits)
add_subdirectory(test.unit.stlsoft.util.count_hexadecimal_digits)
add_subdirectory(test.unit.stlsoft.util.dimensionof)
add_subdirectory(test.unit.stlsoft.util.exception_string)
add_subdirectory(test.unit.stlsoft.util.exception_string_creator)
add_subdirectory(test.unit.stlsoft.util.forward_enums)
add_subdirectory(test.unit.stlsoft.util.inert)
add_subdirectory(test.unit.stlsoft.util.integral_printf_traits)
add_subdirectory(test.unit.stlsoft.util.limit_traits)
add_subdirectory(test.unit.stlsoft.util.minmax)
add_subdirectory(test.unit.stlsoft.util.must_init)
add_subdirectory(test.unit.stlsoft.util.null)
add_subdirectory(test.unit.stlsoft.util.operator_bool)
add_subdirectory(test.unit.stlsoft.util.operator_bool_adaptor)
add_subdirectory(test.unit.stlsoft.util.options_verifier)
add_subdirectory(test.unit.stlsoft.util.pair)
add_subdirectory(test.unit.stlsoft.util.placement_aid)
add_subdirectory(test.unit.stlsoft.util.pod_veneer)
add_subdirectory(test.unit.stlsoft.util.printf_traits)
add_subdirectory(test.unit.stlsoft.util.remove_from_scope)
add_subdirectory(test.unit.stlsoft.util.resizeable_buffer_helpers)
add_subdirectory(test.unit.stlsoft.util.sign_traits)
add_subdirectory(test.unit.stlsoft.util.size_traits)
add_subdirectory(test.unit.stlsoft.util.static_initialisers)
add_subdirectory(test.unit.stlsoft.util.std_swap)
add_subdirectory(test.unit.stlsoft.util.string.snprintf)
add_subdirectory(test.unit.stlsoft.util.string_insertion)
add_subdirectory(test.unit.stlsoft.util.string_switch)
add_subdirectory(test.unit.stlsoft.util.trip_bool)
add_subdirectory(test.unit.stlsoft.util.true_typedef)
add_subdirectory(test.unit.stlsoft.util.zero)

# ############################## end of file ############################# #
