# SIS:AUTO_GENERATED: Remove this line if you edit the file, otherwise it will be overwritten
add_subdirectory(error)
add_subdirectory(test.component.winstl.toolhelp.heap_sequence)
add_subdirectory(test.component.winstl.toolhelp.module_sequence)
add_subdirectory(test.component.winstl.toolhelp.process_sequence)
add_subdirectory(test.component.winstl.toolhelp.sequence_base)
add_subdirectory(test.component.winstl.toolhelp.sequence_value_traits)
add_subdirectory(test.component.winstl.toolhelp.thread_sequence)
