# SIS:AUTO_GENERATED: Remove this line if you edit the file, otherwise it will be overwritten
add_subdirectory(test.unit.winstl.system.commandline_parser)
add_subdirectory(test.unit.winstl.system.console_colour_scope)
add_subdirectory(test.unit.winstl.system.console_ctrl_handler_scope)
add_subdirectory(test.unit.winstl.system.console_functions)
add_subdirectory(test.unit.winstl.system.host_name)
add_subdirectory(test.unit.winstl.system.memory_functions)
add_subdirectory(test.unit.winstl.system.os_version)
add_subdirectory(test.unit.winstl.system.system_info)
add_subdirectory(test.unit.winstl.system.system_information_functions)
add_subdirectory(test.unit.winstl.system.system_traits)
add_subdirectory(test.unit.winstl.system.system_version)
add_subdirectory(test.unit.winstl.system.temporary_file_name)
add_subdirectory(test.unit.winstl.system.user_name)
add_subdirectory(test.unit.winstl.system.version_info)
