# SIS:AUTO_GENERATED: Remove this line if you edit the file, otherwise it will be overwritten
add_subdirectory(number)
add_subdirectory(test.unit.winstl.conversion.a2w)
add_subdirectory(test.unit.winstl.conversion.char_conversions)
add_subdirectory(test.unit.winstl.conversion.int_to_string)
add_subdirectory(test.unit.winstl.conversion.resource_id)
add_subdirectory(test.unit.winstl.conversion.w2a)
add_subdirectory(test.unit.winstl.conversion.w2m)
add_subdirectory(test.unit.winstl.conversion.windows_type_conversions)
