# SIS:AUTO_GENERATED: Remove this line if you edit the file, otherwise it will be overwritten
add_subdirectory(clipboard)
add_subdirectory(diagnostics)
add_subdirectory(dl)
add_subdirectory(exception)
add_subdirectory(filesystem)
add_subdirectory(i18n)
add_subdirectory(memory)
add_subdirectory(performance)
add_subdirectory(process)
add_subdirectory(registry)
add_subdirectory(synch)
add_subdirectory(system)
add_subdirectory(toolhelp)
