# SIS:AUTO_GENERATED: Remove this line if you edit the file, otherwise it will be overwritten
add_subdirectory(test.unit.mfcstl.shims.access.string)
add_subdirectory(test.unit.mfcstl.shims.access.string.CException)
add_subdirectory(test.unit.mfcstl.shims.access.string.cstring)
add_subdirectory(test.unit.mfcstl.shims.access.string.cwnd)
