add_subdirectory(test.unit.stlsoft.conversion.integer_to_string.integer_to_base32_string)
add_subdirectory(test.unit.stlsoft.conversion.integer_to_string.integer_to_base36_string)
add_subdirectory(test.unit.stlsoft.conversion.integer_to_string.integer_to_decimal_string)
add_subdirectory(test.unit.stlsoft.conversion.integer_to_string.integer_to_hexadecimal_string)
add_subdirectory(test.unit.stlsoft.conversion.integer_to_string.integer_to_lc_string)
add_subdirectory(test.unit.stlsoft.conversion.integer_to_string.integer_to_octal_string)
add_subdirectory(test.unit.stlsoft.conversion.integer_to_string.integer_to_string)
add_subdirectory(test.unit.stlsoft.conversion.integer_to_string.integer_to_zeropadded_decimal_string)

# ############################## end of file ############################# #
