# SIS:AUTO_GENERATED: Remove this line if you edit the file, otherwise it will be overwritten
add_subdirectory(error)
add_subdirectory(test.component.winstl.registry.defs)
add_subdirectory(test.component.winstl.registry.functions)
add_subdirectory(test.component.winstl.registry.reg_key)
add_subdirectory(test.component.winstl.registry.reg_key_sequence)
add_subdirectory(test.component.winstl.registry.reg_traits)
add_subdirectory(test.component.winstl.registry.reg_value)
add_subdirectory(test.component.winstl.registry.reg_value_sequence)
add_subdirectory(test.component.winstl.registry.shared_handles)
