# SIS:AUTO_GENERATED: Remove this line if you edit the file, otherwise it will be overwritten
add_subdirectory(test.unit.winstl.shims.conversion.to_FILETIME.DATE)
add_subdirectory(test.unit.winstl.shims.conversion.to_FILETIME.FILETIME)
add_subdirectory(test.unit.winstl.shims.conversion.to_FILETIME.SYSTEMTIME)
add_subdirectory(test.unit.winstl.shims.conversion.to_FILETIME.UDATE)
