if(cstring_FOUND)

	add_subdirectory(test.unit.winstl.diagnostics.C.output_debug_line)
endif(cstring_FOUND)
add_subdirectory(test.unit.winstl.diagnostics.C.printf_debug_string)
add_subdirectory(test.unit.winstl.diagnostics.output_debug_line)
add_subdirectory(test.unit.winstl.diagnostics.printf_debug_string)


# ############################## end of file ############################# #

