if(cstring_FOUND)

	add_subdirectory(test.unit.winstl.diagnostics.output_debug_line.C)
endif(cstring_FOUND)
add_subdirectory(test.unit.winstl.diagnostics.printf_debug_string.C)
add_subdirectory(test.unit.winstl.diagnostics.output_debug_line)
add_subdirectory(test.unit.winstl.diagnostics.printf_debug_string)


# ############################## end of file ############################# #

