# SIS:AUTO_GENERATED: Remove this line if you edit the file, otherwise it will be overwritten
add_subdirectory(test.unit.winstl.window.creation_functions.C)
add_subdirectory(test.unit.winstl.window.font_functions.C)
add_subdirectory(test.unit.winstl.window.functions.C)
add_subdirectory(test.unit.winstl.window.gdi_functions.C)
add_subdirectory(test.unit.winstl.window.menu_functions.C)
add_subdirectory(test.unit.winstl.window.message_functions.C)
add_subdirectory(test.unit.winstl.window.scale_functions.C)
add_subdirectory(test.unit.winstl.window.textmetrics_functions.C)
add_subdirectory(test.unit.winstl.window.colour_constants)
add_subdirectory(test.unit.winstl.window.scale_functions)
add_subdirectory(test.unit.winstl.window.window_traits)
