add_subdirectory(test.unit.stlsoft.string.c_string.strnchr)
add_subdirectory(test.unit.stlsoft.string.c_string.strnicmp)
add_subdirectory(test.unit.stlsoft.string.c_string.strnistrn)
add_subdirectory(test.unit.stlsoft.string.c_string.strnpbrkn)
add_subdirectory(test.unit.stlsoft.string.c_string.strnrchr)
add_subdirectory(test.unit.stlsoft.string.c_string.strnstrn)

# ############################## end of file ############################# #
