# SIS:AUTO_GENERATED: Remove this line if you edit the file, otherwise it will be overwritten
add_subdirectory(test.unit.stlsoft.functional.composite_predicates)
add_subdirectory(test.unit.stlsoft.functional.equal_ptr)
add_subdirectory(test.unit.stlsoft.functional.function_adaptors)
add_subdirectory(test.unit.stlsoft.functional.function_pointer_adaptors)
add_subdirectory(test.unit.stlsoft.functional.indirect_function_pointer_adaptors)
add_subdirectory(test.unit.stlsoft.functional.method_adaptors)
add_subdirectory(test.unit.stlsoft.functional.noop)
add_subdirectory(test.unit.stlsoft.functional.procedure_adaptors)
